---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jaret.
--- DateTime: 1/29/19 11:43 PM
---

-- I'm making this because I hate C++ arrays and doing this in C++ made me want to kms.


originalTable = {"a", "b", "c", "c", "a", "b", "d", "a", "g", "c", "g", "q"}
removedRepeats={}
removedCount={}

print("Original table: "..table.concat(originalTable))

for i=1, #originalTable do
    repeated = false
    for e=1, #removedRepeats do
        if originalTable[i] == removedRepeats[e] then
            repeated = true
            table.insert(removedCount, originalTable[i])
        end
    end
    if repeated == false then
        table.insert(removedRepeats, originalTable[i])
    end
end


print("Removed repeats: "..#removedCount.." New table: "..table.concat(removedRepeats))










